### ISSUE TITLE
Calling an API inside overrideItemForActivityType block

### ISSUE THREAD

**Issue by kgeorgek** [timonus/TJActivityViewController#3]
So I was exploring this great tool, so I was trying to call an API inside the overrideItemForActivityType but it seems it does not work as expected. 

[avc overrideItemForActivityType:"App" withBlock:^id _Nonnull {
        [self createmedium:"App" completion:^(NSString * _Nullable item) { //API Call
            return item; //compiler shows error ie cannot return NSString in void
        }];
}];

This is what I am trying to achieve is there any way we can do?

**Comment by kgeorgek** [comment]
@timonus any idea.

**Comment by timonus** [comment]
The block being passed to `createMedium` needs a return type, it's currently `void` which is why you're getting that error. Furthermore, you need to return a value from the `createMedium` method out of the block that contains it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timonus** [comment]
So, something like

```
[avc overrideItemForActivityType:"App" withBlock:^id _Nonnull {
    **return **[self createmedium:"App" completion:^**id **(NSString * _Nullable item) { //API Call
        return item; //compiler shows error ie cannot return NSString in void
    }];
}];
```

stuff I added is surrounded in `**`'s
