### ISSUE TITLE
Instagram Stories not showing

### ISSUE THREAD

**Issue by PratikKhunt** [timonus/TJActivityViewController#5]
Hello,

I want to add activity for sharing on instagram stories. I want activity type for that

Thanks

**Comment by timonus** [comment]
Instagram doesn't have a dedicated Stories share extension. You can use `TJActivityViewController` to override Instagram's entry in the share sheet to provide stories sharing options using [this API](https://developers.facebook.com/docs/instagram/sharing-to-stories/).
