### ISSUE TITLE
Not seems to be working on IOS 14.5 Swift Project 

### ISSUE THREAD

**Issue by sluzhynskyi** [timonus/TJActivityViewController#6]
My simple snippet
![image](https://user-images.githubusercontent.com/44615981/125599999-20f164a9-af3c-4e8d-9b26-1d3a2191c489.png)
And as a result it is a same as simple UIActivityViewController action
![IMG_753F93019D70-1](https://user-images.githubusercontent.com/44615981/125599613-1cb894c8-4fa3-4ea8-b8d7-c48b4e5da4b2.jpeg)

**Comment by timonus** [comment]
Hey there, the reason this isn't working is that you're using a regex string as an activity type. You should be using

```
overrideActivityTypeMatchingRegex(TJActivityViewControllerInstagramRegexString) {
...
```

instead of

```
overrideActivityType(TJActivityViewControllerInstagramRegexString) {
...
```

I'll update the API to try to make this less easy to mess up in the future!

**Comment by sluzhynskyi** [comment]
Tried your way,  Swift doesn't see that method with this signature
![image](https://user-images.githubusercontent.com/44615981/125680914-f8d72370-f42c-4bc7-86b5-05240633e3ff.png)


However, code below works like a charm
```Swift
        activityViewController.overrideActivityType(matchingRegex: TJActivityViewControllerInstagramRegexString) {
            print("Hello world")
        }
```

Thank You

**Comment by timonus** [comment]
Oh sorry, I'm a Swift n00b so probably messed up the syntax. Happy it worked!
